### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by jakubartur** [stakecube/StakeCubeCoin#11]
new version compile error

  CXX      bls/libsccconsensus_la-bls.lo
In file included from bls/bls.cpp:5:0:
./bls/bls.h:14:10: fatal error: chiabls/bls.hpp: No such file or directory
 #include <chiabls/bls.hpp>

**Comment by jakubartur** [comment]
me compile done me look version StakeCubeCoin Daemon version v3.1.0 , what link new version 3.2 , no upload github ? strange update version no add new version github

**Comment by JSKitty** [comment]
Hey! v3.2 has been released now, it should be a bit easier to compile as dependencies have been upgraded and unneeded ones have been trimmed, so give it a shot!

Closing this for now, but feel free to open it back up if you're still having compile issues, or join our Discord for additional support!
