### ISSUE TITLE
sccd attempts to create a Tor v2 address (and fails)

### ISSUE THREAD

**Issue by KenSharp** [stakecube/StakeCubeCoin#12]
Tor v2 addresses are deprecated. sccd attempts to create a Tor .onion address using this old format, if enabled. This will (and should) fail with the latest Tor client.

`tor: Add onion failed; error code 513`

The client needs to be updated to use the new and more secure Tor v3 addresses.

This commit shows the solution in the Bitcoin core client: https://github.com/bitcoin/bitcoin/pull/19954/commits/dcf0cb477699d11afd0ff37c8bfb2b1b4f7f1ee5
It doesn't look like Dash implemented this change.

This should work in sccd but I cannot currently build to test this.

Previously sccd worked fine with Tor v2 addresses.

**Comment by JSKitty** [comment]
Howdy! @KenSharp Tor v3 support should be improved in the latest release. :onion:

Will close the issue for now, but feel free to open it back up if it's not as expected!
