### ISSUE TITLE
command line switches causing segfault

### ISSUE THREAD

**Issue by KenSharp** [stakecube/StakeCubeCoin#2]
Running the application with _--help_ or _-help_ immediately causes a segfault.

```
$ scc-3.0.1-linux -help
Posix Signal: Segmentation fault
No debug information available for stacktrace. You should add debug information and then run:
scc-3.0.1-linux -printcrashinfo=bvjugqzninzgc43ijfxgm3ybaahxgy3dfuzs4mbogewwy2loov4caudponuxqictnftw4ylmhiqfgzlhnvsw45dboruw63ramzqxk3dubg2obfyaaaaaaafazat5ifjjaaaga7qhaeaaaaaar76bwaaaaaaab2dldqaaaaaaacasgiqaaaaaaaalvelaaaaaaaajo6zv2mkssaaajffrqaaaaaaaaaa=
Aborted (core dumped)
```

And with _-version_:
```
$ scc-3.0.1-linux -version
Posix Signal: Segmentation fault
No debug information available for stacktrace. You should add debug information and then run:
scc-3.0.1-linux -printcrashinfo=bvjugqzninzgc43ijfxgm3ybaahxgy3dfuzs4mbogewwy2loov4caudponuxqictnftw4ylmhiqfgzlhnvsw45dboruw63ramzqxk3dubg2obfyaaaaaaafafcwaygjkaaaga7qhaeaaaaaar76bwaaaaaaab2dldqaaaaaaacasgiqaaaaaaaalvelaaaaaaaajpw5zbmmsuaaajffrqaaaaaaaaaa=
Aborted (core dumped)
```

Adding the _printcrashinfo_ as suggested creates a dialog with the same information, rather than printing on the command line, but makes no real difference.

Running the application with an invalid switch allows the application to load normally:

`$ scc-3.0.1-linux -cake -biscuits -cheese` for example, runs without issue.

**Comment by JSKitty** [comment]
`sccd -cake -biscuits -cheese` is indeed the correct way to run StakeCubeCoin Core **/s**

Will investigate this once I get some time, certainly interesting that it's working exactly the opposite as it should haha.

Which binary did you run these commands on? the daemon / CLI binaries? or the QT (GUI) binaries?

**Comment by KenSharp** [comment]
..I should have mentioned that.

The GUI. The CLI seems to work fine.

**Comment by JSKitty** [comment]
Ah, makes a bit more sense, Daemon / CLI are intended for CLI commands, however, the GUI *should* still respond to CLI commands like `-help` and such, and certainly shouldn't segfault, so I'll investigate that in due time!

**Comment by sc-9310** [comment]
IIRC GUI use same command line options as daemon with additional options for UI but not CLI. 
-sporkkey=xx, -datadir=xx etc working fine, tested on win and linux. Nevertheless, runtime exception should be handled, agree.

**Comment by Liquid369** [comment]
Hello,

Will be fixed in the next release, have found the issue related.

Thanks!
