### ISSUE TITLE
Compile error (linker:  undefined reference to symbol '_ZN5boost6system15system_categoryEv') 

### ISSUE THREAD

**Issue by Ur-Quan** [stakecube/StakeCubeCoin#20]
Hi. As subject says. Did `git clone`. Ubuntu 18.10, g++ 9. Output:

/usr/bin/ld: sccd-sccd.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.65.1: error adding symbols: DSO missing from command line

**Comment by Liquid369** [comment]
Hello

When following the build documents, are you building using the depends system or are you installing the depends yourself? 
It seems there is one that was missed, 
either try ```sudo apt-get install libboost-all-dev``` or rebuilding in the ```depends``` folder

**Comment by squidicuzz** [comment]
Closing stale issue.  Please re-open if still have problems compiling.
