### ISSUE TITLE
sccd v3.3.0 crashed with Assertion failure (processing an RPC from scc-cli?)

### ISSUE THREAD

**Issue by walkjivefly** [stakecube/StakeCubeCoin#24]
### Describe the issue
sccd v3.3.0 (running as a masternode) crashed, possibly while processing an RPC from scc-cli.

#### If so, please list the steps to reproduce below:
1. start sccd
2. scc-cli help
3.

### Expected behaviour
sccd should not crash when responding to an scc-cli RPC

### Actual behaviour
sccd crashed handling an scc-cli RPC

### What version of SCC Core are you using?
SCC Core version v3.3.0.0-927df60c4b82 (release build)

### Machine specs:
- OS: Ubuntu 18.04 LTS
- CPU: 8vCPU
- RAM: 30GB
- Disk size: 1.2TB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
debug.log ends with 
```
2022-10-17T08:27:31Z Assertion failure:
  assertion: type == Type::ARR || type == Type::OBJ
  file: ./rpc/util.h, line: 164
  function: RPCArg::RPCArg(const string&, const RPCArg::Type&, const Fallback&, const string&, const std::vector<RPCArg>&, const string&, const std::vector<std::__cxx11::basic_string<char> >&)
No debug information available for stacktrace. You should add debug information and then run:
sccd -printcrashinfo=brjugq2dojqxg2cjnztg6aiaarzwgy3e7utqcqltonsxe5djn5xcaztbnfwhk4tfhifcaidbonzwk4tunfxw4oraor4xazjahu6savdzobstuosbkjjca7d4eb2hs4dfea6t2icupfygkor2j5beucraebtgs3dfhiqc4l3sobrs65lunfwc42bmebwgs3tfhiqdcnrubiqcaztvnzrxi2lpny5causqinaxezz2hjjfaq2bojtsqy3pnzzxiidtorzgs3theywcay3pnzzxiicskbbuc4thhi5fi6lqmutcyiddn5xhg5baizqwy3dcmfrwwjrmebrw63ttoqqhg5dsnfxgojrmebrw63ttoqqhg5dehi5hmzldorxxepcskbbuc4thhytcyiddn5xhg5baon2he2lom4tcyiddn5xhg5baon2gior2ozswg5dpoi6hg5dehi5f6x3dpb4dcmj2hjrgc43jmnpxg5dsnfxgopddnbqxeprahytcsdmglf5qaaaaaaaaw4ruaaaaaaaa2qedoaaaaaaabirngqaaaaaaact64piaaaaaaaey6i6qaaaaaaakeljuaaaaaaaaqiet4aaaaaaabxebk4aaaaaaaaez4vyaaaaaaah7iw7qaaaaaaanw5qaobgssaaad4tfo32nfeaaaaa=
```

I tried running `scc-cli help` on my local PC collateral wallet. sccd crashed there too with the same assertion failure in debug.log

**Comment by Liquid369** [comment]
Hello,

Seems it was an issue that persisted for awhile, we had a prior issue with it as well
https://github.com/stakecube/StakeCubeCoin/issues/2 but it will be rectified in the next upcoming update.

We appreciate you guys reporting these things so we can fix them.

Thanks!

**Comment by walkjivefly** [comment]
It's a shame the workaround from #2 of adding an invalid option no longer works ;-)

**Comment by Liquid369** [comment]
Closing as this was resolved with the other fixes as well from other issue
