### ISSUE TITLE
Unexpected behaviour from scc-cli

### ISSUE THREAD

**Issue by walkjivefly** [stakecube/StakeCubeCoin#25]
### Describe the issue
(backports branch) `scc-cli help` says the wallet must be unlocked. It would be more useful if it displayed the list of available options and commands.

Apparently the help command only works if you already know which command you want help with, eg:
`scc-cli help help`

### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. scc-cli help
2.
3.

### Expected behaviour
`scc-cli help` should operate like "every" other `xxx-cli help` and list all the available commands.

### Actual behaviour
```
mark (backports) StakeCubeCoin $ ./src/scc-cli help
error code: -13
error message:
Error: Please enter the wallet passphrase with walletpassphrase first.
```

### What version of SCC Core are you using?
```mark (backports) StakeCubeCoin $ ./src/scc-cli --version
SCC Core RPC client version v3.3.0.0-b87b357f0
```

### Any extra information that might be useful in the debugging process.
```
mark (backports) StakeCubeCoin $ ./src/scc-cli -help
SCC Core RPC client version v3.3.0.0-b87b357f0

Usage:  scc-cli [options] <command> [params]  Send command to SCC Core
or:     scc-cli [options] -named <command> [name=value]...  Send command to SCC Core (with named arguments)
or:     scc-cli [options] help                List commands
or:     scc-cli [options] help <command>      Get help for a command

Options:
...
mark (backports) StakeCubeCoin $ ./src/scc-cli help help
help ( "command" "subcommand" )

List all commands, or get help for a specified command.

Arguments:
1. command       (string, optional, default=all commands) The command to get help on
2. subcommand    (string, optional, default=all subcommands) The subcommand to get help on. Please note that not all subcommands support this at the moment

Result:
"str"    (string) The help text

mark (backports) StakeCubeCoin $ ./src/scc-cli help all
help: unknown command: all
```

**Comment by Liquid369** [comment]
Good catch, that should now fixed in the backports branch if you are willing to give it another test

**Comment by walkjivefly** [comment]
Better! But
```
mark (backports) StakeCubeCoin $ scc-cli help
...
== Mining ==
./rpc/util.h:181 (RPCArg)                                <<<<<<<<<<<<<<<<<< OOPS!
getmininginfo
getnetworkhashps ( nblocks height )
pprpcsb "header_hash" "mix_hash" "nonce"
...
```

**Comment by Liquid369** [comment]
Fair...lol
While fixing up this one, came across this myself a bit above it.
![Screen Shot 2022-10-18 at 9 33 06 AM](https://user-images.githubusercontent.com/45834289/196492799-a4acce7b-dcfb-4faa-92ea-9bf809f94676.png)
So now both should be fixed if you fancy giving it another try ^^

**Comment by walkjivefly** [comment]
With the latest on the backports branch, the blockchain one I missed is fixed but the mining one is still there.

**Comment by Liquid369** [comment]
Fully resolved with the latest commit on backports branch!
![Screen Shot 2022-10-19 at 7 41 01 AM](https://user-images.githubusercontent.com/45834289/196693455-d193b39a-f364-4c08-8da0-df534c3b0a6b.png)

**Comment by walkjivefly** [comment]
Confirmed in https://github.com/stakecube/StakeCubeCoin/commit/3d28d87066f724626fcbbf7031e949ad935e2531

Thank you.
