### ISSUE TITLE
Stale Link

### ISSUE THREAD

**Issue by 2a5A1Ghu1** [stakecube/StakeCubeCoin#28]
I believe this link is stale now

https://github.com/stakecube/StakeCubeCoin/blob/ed802b93ced38828e4a4d743e31602465dd0173f/depends/packages/immer.mk#L3

**Comment by 2a5A1Ghu1** [comment]
here is the proper link https://github.com/arximboldi/immer/archive/refs/tags/v0.6.2.tar.gz

**Comment by squidicuzz** [comment]
Updated link: 
![image](https://github.com/stakecube/StakeCubeCoin/assets/1578496/17475b0a-f584-40a5-b339-ae9e42f18927)
https://github.com/squidicuzz/StakeCubeCoin/commit/a20fdc1a9a1c067e72a6444abb564f0f66c28770

Testing...

**Comment by squidicuzz** [comment]
This change seems to have resolved compile issue for the Qt build process.
