### ISSUE TITLE
Auto Backup of wallet no longer functions?

### ISSUE THREAD

**Issue by squidicuzz** [stakecube/StakeCubeCoin#33]
It is expected that each time the wallet starts, a backup of the `wallet.dat` or whatever loaded wallet is to be created.  So it seems this auto-backup feature of the wallet is no longer functional in `v3.4.0` of SCC Core and was not noticed before release.

*Note*; A backup will still be taken whenever a new wallet is created, this backup contains 1000 pregenerated keys (generally).

A patch has been added for the wallet backup function in #32 to force a backup when the wallet starts.

Additional debug added as well.
![image](https://github.com/stakecube/StakeCubeCoin/assets/1578496/b7a2c625-b1b8-48b2-af8a-23f44bb5d8fc)

**Comment by grigzy28** [comment]
Found where it got broken....  wallet/wallet.cpp
function AutoBackupWallet got partially rewritten along with several other routines in walletdb.cpp and bdb.cpp.

The routine is working as it should EXCEPT it's not getting to the backup part of the routine which is the last step.  It is "aborting" or "finishing" the verify process and then "exiting" the whole series of routines somewhere.  I am not a good programmer but was able to trace it down that far.

**Comment by grigzy28** [comment]
Original Code
![image](https://github.com/stakecube/StakeCubeCoin/assets/30666305/37dfa7b3-49ff-46ce-a206-5723e01dc66b)
Modified Code
![image](https://github.com/stakecube/StakeCubeCoin/assets/30666305/ee57195e-4a11-4916-9000-8f6e165eb6f8)


It does compile and load and create the backup as intended.  Not sure if the result would be the same if it there was a corrupted or other error loading the wallet file.

**Comment by squidicuzz** [comment]
> Found where it got broken.... wallet/wallet.cpp function AutoBackupWallet got partially rewritten along with several other routines in walletdb.cpp and bdb.cpp.

Right, but I have modified some of the code in those files in attempts to fix this issue.  So those changes were me, just recently.  I traced it down to around the some points as well though.  Thank you for verifying this.

I will check more and test those modifications you pointed out. 👍

**Comment by grigzy28** [comment]
The original code is from the 3.4.0 official source code build b6fb60c33 and not the modified develop branch code with those changes you had made the other day.  I decided to do that since you had made those other changes and didn't want to collide with your changes and not get a valid result.
