### ISSUE TITLE
OSX executable?

### ISSUE THREAD

**Issue by mohker-83010** [stakecube/StakeCubeCoin#39]
OSX executable?

v3.4.1.1 "latest release"

EYE find this puzzle.
have some button smash capability.
maybe EYE break this one out into pieces and it work.

:D

**Comment by squidicuzz** [comment]
Should be out soon.  Hang tight.

**Comment by mohker-83010** [comment]
scc-3.4.1.0-Qt-unsigned.dmg -- tested

loads "splash screen"

OSX returns

“SCC Core” cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.
This item is on the disk image “scc-3.4.1.0-Qt-unsigned.dmg”. Safari downloaded this disk image today at 1:33 AM.

eject disk image - button
cancel - button

(work around most likely possible)

**Comment by mohker-83010** [comment]
currently running 3.3.1 on OSX
tinkered around with the available files and got the wallet running.
might be the disk image version.
used real troll easy smash button process :D

back tracking through for development

scc-3.3.1-osx64.tar --- package

results on terminal load.

“scc-qt” is damaged and can’t be opened. You should move it to the Trash.
The application “Terminal” can’t be opened.

“scc-wallet” cannot be opened because it is from an unidentified developer.
macOS cannot verify that this app is free from malware.

(most likely a work around for this)

**Comment by mohker-83010** [comment]
scc -3.4.0-osx-unsigned-qt.dmg ----  tested

loads "splash screen"

OSX returns

“SCC Core” cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.
This item is on the disk image “scc-3.4.0-osx-unsigned-qt.dmg”. Safari downloaded this disk image today at 2:57 AM.

(most likely a workaround for this)

**Comment by mohker-83010** [comment]
OSX error message.

macOS cannot verify that this app is free from malware.

https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac


Apple can’t check app for malicious software
Using an app that can’t be checked for malicious software might harm your Mac or compromise your privacy. If you’re certain that the app you want to use is from a trustworthy source, you can override your Mac security settings to open it.
In the Finder  on your Mac, locate the app you want to open.
Don’t use Launchpad to locate the app.
Control-click the app icon, then choose Open from the shortcut menu.
Click Open.
The app is saved as an exception to your security settings, and you can open it at any time by double-clicking it, just as you do with any registered app.
Note: You can also grant an exception for a blocked app by clicking the Open Anyway button in Privacy & Security settings. This button is available for about an hour after you try to open the app.
To change these settings on your Mac, choose Apple menu  > System Settings, then click Privacy & Security  in the sidebar. (You may need to scroll down.)
You can learn more about how and why your Mac is protected. See the Apple Support article [Safely open apps on your Mac](https://support.apple.com/HT202491).



so dat be lookin like duh workaround. :D

**Comment by mohker-83010** [comment]
https://support.apple.com/en-us/HT202491


Safely open apps on your Mac
macOS includes a technology called Gatekeeper, which is designed to make sure that only trusted software runs on your Mac.

By default, macOS Catalina and later also require software to be notarized, so that you can be confident that the software you run on your Mac doesn't contain known malware. An app that has been notarized by Apple indicates that Apple checked it for malicious software and none was detected.

[
](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution)

Notarizing macOS software before distribution
Give users even more confidence in your macOS software by submitting it to Apple for notarization.

Overview

Notarization gives users more confidence that the Developer ID-signed software you distribute has been checked by Apple for malicious components. Notarization is not App Review. The Apple notary service is an automated system that scans your software for malicious content, checks for code-signing issues, and returns the results to you quickly. If there are no issues, the notary service generates a ticket for you to staple to your software; the notary service also publishes that ticket online where Gatekeeper can find it.
When the user first installs or runs your software, the presence of a ticket (either online or attached to the executable) tells Gatekeeper that Apple notarized the software. Gatekeeper then places descriptive information in the initial launch dialog to help the user make an informed choice about whether to launch the app.


You can notarize several different types of software deliverables, including:
macOS apps
Non-app bundles, such as kernel extensions
Disk images (UDIF format)
Flat installer packages
Notarization also protects your users if your Developer ID signing key is exposed. The notary service maintains an audit trail of the software distributed using your signing key. If you discover unauthorized versions of your software, you can work with Apple to revoke the tickets associated with those versions.

Notarization requires Xcode 10 or later. Building a new app for notarization requires macOS 10.13.6 or later. Stapling an app requires macOS 10.12 or later.
Apple's notary service requires you to adopt the following protections:
Enable code-signing for all of the executables you distribute, and ensure that executables have valid code signatures, as described in [Ensure a valid code signature](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087735).




and dat be lookin like duh workaround for duh workaround. :D

**Comment by mohker-83010** [comment]
3.4.1.1. Source code (zip)

contents:

macOS Build Instructions and Notes
doc/build-osx.md

-------------------------

reference to some build tools "Homebrew"

https://en.wikipedia.org/wiki/Homebrew_(package_manager)

Homebrew is written in the [Ruby programming language](https://en.wikipedia.org/wiki/Ruby_programming_language) and targets the version of Ruby that comes installed with the macOS operating system.

(possible workaround without these "build tools")

-------------------------

Admiral Scragli breaking it down base logic "Homebrew"in:

https://en.wikipedia.org/wiki/MacOS
https://en.wikipedia.org/wiki/Mach_(kernel)
https://en.wikipedia.org/wiki/XNU
https://en.wikipedia.org/wiki/Darwin_(operating_system)

-------------------------

appears to be a build from source Darwin/OSX file in packages.
(untested but it loads in Xcode)

3.4.1.1. Source code/depends/builders/darwin.mk

seems possible to search through DASH and BTC for the same file, might be a more recent version.

-------------------------

3.4.1.1. Source code/COPYING

The MIT License (MIT)

Copyright (c) 2009-2020 The Bitcoin Core developers
Copyright (c) 2009-2020 Bitcoin Developers
Copyright (c) 2014-2020 The Dash Core developers
Copyright (c) 2018-2022 The SCC Core Developers

----------------------------
3.4.1.1. Source code

doc/build-generic.md
doc/build-unix.md

(possible information on searching for Darwin/OSX equivalency build tools)

------------------------------


How to use the Swift Package Manager with dependencies stored in private repositories?

https://stackoverflow.com/questions/47842479/how-to-use-swift-package-manager-with-private-repos

A solution, for Unix-like systems, is to use SSH git URLs and add Host configurations to ~/.ssh/config. This approach works for both macOS/Linux command line and Xcode.

Use a ssh form for the dependency url in Package.swift.

// swift-tools-version:4.0
import PackageDescription
    
let package = Package(
  name: "Example",
  dependencies: [
    .package(url: "git@gitlab.com.myteam:abc/private-repo.git", .branch("develop") ),
  ],
)

In the above example, gitlab.com.myteam corresponds to a Host in ~/.ssh/config

### GITLAB  WorkTeamOne
Host gitlab.com.workteam
  HostName gitlab.com
  User git
  IdentityFile  ~/.ssh/my_work_key_rsa
  UseKeychain yes     # for macOS keychain
  AddKeysToAgent yes  # for macOS keychain
  PreferredAuthentications publickey
 
### GITLAB  Hobby
Host gitlab.com.hobby
  HostName gitlab.com
  User git
  IdentityFile  ~/.ssh/my_hobby_key_rsa
  UseKeychain yes     # for macOS keychain
  AddKeysToAgent yes  # for macOS keychain
  PreferredAuthentications publickey

Generate and apply SSH key pairs, as needed, for an individual's online git service account.

ssh-keygen \
   -b 4096 \
   -t rsa \
   -C "my_work_username@example.com" \
   -f ~/.ssh/my_work_key_rsa

Each team member could setup an individual, corresponding Host ssh configuration. The Host would be the same, however, the actual public/private key pairs (a) are specific to the user, (b) can be managed separately from any of the code development and (c) can be used automatically after the setup.


------------------------

dis be lookin like how you make a SCC App and put it on the App Store for OSX at Apple :D

**Comment by mohker-83010** [comment]
Darwin/OSX/Xcode Official tools

Building from the Command Line with Xcode FAQ




https://developer.apple.com/library/archive/technotes/tn2339/_index.html

the search reference on this document is not easy troll button smash, possibly in need of update.
working through process.

----notes-----

(update to latest official version of OSX.)

updated to Sonoma 14

(checked for updates after install)

(also update to latest version of Xcode in App Store)
(proceeded forward with Xcode 14.2, needed update to 15, version shows as Xcode.app below)


system settings / general / software update

"Command Line Tools for Xcode 15"
The Command Line Tools enable UNIX-style development via Terminal by installing command line developer tools, as well as macOS SDK frameworks and headers. Many useful tools are included, such as the Apple LLVM compiler, linker, and Make. If you use Xcode, these tools are also embedded within the Xcode IDE.

(available for update)


appears that the terminal command line stuff for this is unnecessary.

software updates page has also been updated according to latest version of software running.


possible terminal command line install ---   "xcode-select --install"
result of command after automatic updates.

(xcode-select: note: Command line tools are already installed. Use "Software Update" in System Settings or the softwareupdate command line interface to install updates)

Printing the version of Xcode currently used by the command-line tools.

(archive example above:)
$ xcode-select --print-path
 /Applications/Xcode8.3.3/Xcode.app/Contents/Developer

(current result:)
$ xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

(after updates Xcode 15 and Command Line Tools for Xcode 15)

Terminal command line:

(what happens if EYE try to pull command list from "make")
$ make /?

(result)

You have not agreed to the Xcode and Apple SDKs license. You must agree to the license below in order to use Xcode.
Press enter to display the license:

Xcode and Apple SDKs Agreement
(pages of data)

Agreeing to the Xcode and Apple SDKs license requires admin privileges, please accept the Xcode license as the root user (e.g. 'sudo xcodebuild -license').

----------(easy troll smash button it work! on to next objective.)----------
$ sudo xcodebuild -license
You have not agreed to the Xcode and Apple SDKs license. You must agree to the license below in order to use Xcode.
Press enter to display the license:


By typing 'agree' you are agreeing to the terms of the software license agreements. Any other response will cancel. [agree, cancel]
agree
You can review the license in Xcode’s About window, or at: /Applications/Xcode.app/Contents/Resources/en.lproj/License.rtf

(now this look like linux type stuff. level up!) :D

(now what does "make" do?)

$ make /?

result:

make: *** No rule to make target `/?'.  Stop.

("make" thingy works in Xcode terminal command now. sweet) :D

_______________________________

(now back to) 
3.4.1.1. Source code

doc/build-generic.md
doc/build-unix.md


(((((((((((((doc/build-unix.md)))))))))))))))))
(code lines 8-12)
Base build dependencies

Building the dependencies and SCC Core requires some essential build tools and libraries to be installed before.

Run the following commands to install required packages:

((((((((notes on official OSX Apple tools above))))))))

(code lines 42-45)
Building
Follow the instructions in [build-generic](build-generic.md)

((((((((((((((((doc/build-generic.md)))))))))))))))
(code lines 11-14)
Required build tools and environment

Building the dependencies and SCC Core requires some essential build tools to be installed before. Please see
[build-unix](build-unix.md), [build-osx](build-osx.md) and [build-windows](build-windows.md) for details.

(build-osx.md currently references unnecessary "Homebrew" tools) 
(OSX build from source with official tools is a work in progress)

(code lines 16-19)
Building dependencies
SCC inherited the `depends` folder from Bitcoin, which contains all dependencies required to build SCC. These
dependencies must be built before SCC can actually be built. To do so, perform the following:

(code line 23)
$ make -j4 # Choose a good -j value, depending on the number of CPU cores available
(got to the "make" "unix like" terminal command above)

(on to looking for the bitcoin 'depends' folder, maybe some up to date OSX install information)

https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md
https://github.com/litecoin-project/litecoin/blob/master/doc/build-osx.md

(bitcoin and Litecoin both in need of pull requests, no up to date information)

https://github.com/plotly/dash

(DASH is structured different, where duh doc folder at?) :D 

((((((((((((((((((((on to bitcoin and Litecoin generic/unix build instructions)))))))))))))))))))))))

https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md
"make" command reference
no doc/build-generic.md 

https://github.com/litecoin-project/litecoin/blob/master/doc/build-unix.md
"make" command reference
no doc/build-generic.md


bitcoin core build dependencies
https://github.com/bitcoin/bitcoin/blob/master/doc/dependencies.md


(((((((((((back to SCC core)))))))))))))

(command line 37)
Building SCC Core

(command line 51)
- `x86_64-apple-darwin19` for macOS  
(kernel OS reference, out of date)

a search for "x86_64-apple-darwin19" resulted in:
I check "zsh --version" in terminal and my zsh version is still "zsh 5.7.1 (x86_64-apple-darwin19.0)(https://discussions.apple.com/thread/253918382)

a Terminal command line of "zsh --version" results in:
$ zsh --version
zsh 5.9 (x86_64-apple-darwin23.0)


((((((((((on to testing build terminal commands))))))))))))))

doc/build-generic.md

$ ./autogen.sh
$ ./configure --prefix=`pwd`/depends/<host>
$ make
$ make install # optional

(((((((((((((((($./autogen.sh))))))))))))))))))

Terminal (folder: StakeCubeCoin 3.4.1.1 source code)
$ ./autogen.sh
result:
configuration failed, please install autoconf first

(code lines 10-15)
if [ -z "${LIBTOOLIZE}" ] && GLIBTOOLIZE="$(command -v glibtoolize)"; then
  LIBTOOLIZE="${GLIBTOOLIZE}"
  export LIBTOOLIZE
fi
command -v autoreconf >/dev/null || \
  (echo "configuration failed, please install autoconf first" && exit 1)

(appears to have failed to call libtools)

((((((((((((((((((( libtool )))))))))))))))))))))))
Terminal (folder: StakeCubeCoin 3.4.1.1 source code)
$ libtool
result:
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: no output file specified (specify with -o output)
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]

(((((((((((((($./configure))))))))))))))))
Terminal (folder: StakeCubeCoin 3.4.1.1 source code)
$ ./configure
result:
-bash: ./configure: No such file or directory
configure.ac(in folder, if this is the file)
(open for inspection)
result:
There is no application set to open the document “configure.ac”.
Search the App Store for an application that can open this document, or choose an existing application on your computer.
"choose an application" button
search for Xcode
configure.ac opens in Xcode

doc/build-generic.md
(code line 42, and 47)

(ran after "make" depends, $./autogen.sh)
(configuration failed, please install autoconf first)

$ ./configure --prefix='pwd' /depends/x86_64-apple-darwin23.0

result:

-bash: ./configure: No such file or directory

$ make
make: *** No targets specified and no makefile found.  Stop.
$ make install
make: *** No rule to make target `install'.  Stop.

(depends/Makefile appears to be in need of updating)

(((((((((((((((make))))))))))))))))))))
Terminal (folder: StakeCubeCoin 3.4.1.1 source code)
$ make
result:
make: *** No targets specified and no makefile found.  Stop.

$ make --help
result:
Usage: make [options] [target] ...
Options:
-(list of commands)
This program built for i386-apple-darwin11.3.0
Report bugs to <bug-make@gnu.org>

doc/build-generic.md
(code line 23)

(Terminal opened at depends folder)

$ make -j4            // # Choose a good -j value, depending on the number of CPU cores available

result:
(appears that "boost" may have been built)
(pages of data, some build actions, looks like the depends/Makefile is needing updating)

$ sudo make

different results:
examples:

shasum: copy/depends/patches/qt/mac-qmake.conf: No such file or directory
(somewhere around 22 items like this called for in the depends/patches folder)


((((((((((((( depends/README.md ))))))))))))))))))

(code lines 7 and 9)
To build for another arch/OS:
make HOST=host-platform-triplet

( $ zsh --version, for "host-platform-triplet" )

$ make HOST=x86_64-apple-darwin19
$ make HOST=x86_64-apple-darwin23.0

(results appear to be the same as above)

( perl is running when missing components are being generated, could be perl utils needed )
((((((( perl )))))))))
$ perl --version
This is perl 5, version 30, subversion 3 (v5.30.3) built for darwin-thread-multi-2level
(with 2 registered patches, see perl -V for more detail)


(code line 40, package install references)

sudo apt-get install curl librsvg2-bin libtiff-tools bsdmainutils imagemagick libcap-dev libz-dev libbz2-dev python3-setuptools libtinfo5

(apt-get is a package manager, have used this on linux before)
(contains a list of packages or equivalencies to search for in Darwin/OSX)

curl librsvg2-bin libtiff-tools bsdmainutils imagemagick libcap-dev libz-dev libbz2-dev python3-setuptools libtinfo5

(code lines 42-45)
Note: You must obtain the macOS SDK before proceeding with a cross-compile.
Under the depends directory, create a subdirectory named `SDKs`.
Then, place the extracted SDK under this new directory.
For more information, see [SDK Extraction](../contrib/macdeploy/README.md#sdk-extraction).



(on to contrib/macdeploy/README.md)

### Step 1: Obtaining `Xcode.app`

(code line 35)
git clone https://github.com/bitcoin-core/apple-sdk-tools.git
(link)
https://github.com/bitcoin-core/apple-sdk-tools

(suggested but seems unnecessary)

(code lines 42-46)
On macOS the process is more straightforward:

```bash
xip -x Xcode_12.1.xip
```

(run alone in terminal result)

$ xip -x Xcode_15.xip
xip: error: input file "_______" not found.

(run attempted to generate file from Xcode)

$ xip -x /applications/Xcode.app Xcode_15.xip
$ sudo xip -x /applications/Xcode.app Xcode_15.xip
xip: error: The archive “Xcode” is damaged and can’t be expanded.
(appears to have some sort of protection for this, should work)

(step: 1 appears to be irrelevant)

### Step 2: Generating
(code line 57)
./contrib/macdeploy/gen-sdk '/path/to/Xcode.app'

(gen-sdk inspected in Xcode appears to be useful but further along in compiling than "libtools" stuff)

(rest of document has what appears to be notes on generating the GUI executable for Darwin/osx)

((((((((((((( xip --version ))))))))))))
$ xip --version
xip: unrecognized option `--version'
Usage: xip [options] --sign <identity> <input-file> [ <input-file> ... ] <output-xip-file>
Usage: xip --expand <input-file>


((((((((((((( curl )))))))))))))))
$ curl --version
curl 8.1.2 (x86_64-apple-darwin23.0)


(((((((((((( git ))))))))))))))))))

$ git

result:

usage: git

(usage commands)

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
See 'git help git' for an overview of the system.

(appears possible to pull the repo from terminal, untested)

(((((((((((((( Clang )))))))))))))))))))
Terminal (folder: StakeCubeCoin 3.4.1.1 source code)
$ clang

result:

clang: error: no input files

(((((((((((((((( GCC )))))))))))))))))
Terminal (folder: StakeCubeCoin 3.4.1.1 source code)

$ gcc

result:

clang: error: no input files

(appears gcc is somehow connected to clang)

(((((((((((((((( Python )))))))))))))))))
Terminal

$ python3 --version

result

Python 3.9.6

listed as a dependency on https://github.com/bitcoin/bitcoin/blob/master/doc/dependencies.md
latest version as of this writing, Python 3.8
(many references to "Homebrew" when searching for Xcode python, also unnecessary)

https://www.python.org/downloads/macos/
(installer available, untested)

(((((((((((((((( list of tools unavalible ))))))))))))))
doc/build-netbsd.md
autoconf
automake
boost
gmake
libevent
pkg-config
python37
systemtap
glibc

depends/README.md
librsvg2-bin 
libtiff-tools 
bsdmainutils 
imagemagick 
libcap-dev 
libz-dev 
libbz2-dev 
python3-setuptools 
libtinfo5

(((((((((((( "boost" is missing? ))))))))))))))))))

what is "boost"?

https://www.boost.org/doc/libs/1_83_0/more/getting_started/unix-variants.html

5.2.2   Identify Your Toolset

First, find the toolset corresponding to your compiler in the following table (an up-to-date list is always available [in the Boost.Build documentation
https://www.boost.org/doc/libs/1_83_0/tools/build/doc/html/index.html#bbv2.reference.tools

darwin | Apple Computer | Apple's version of the GCC toolchain with support for Darwin and MacOS X features such as frameworks.

("boost" is somewhere, "boost" is hiding.)


((((((((((((((( "gmake" is missing? ))))))))))))))))))))

"gmake" is "make"?

https://www.gnu.org/software/make/

GNU Make is a tool which controls the generation of executables and other non-source files of a program from the program's source files.

Make gets its knowledge of how to build your program from a file called the makefile, which lists each of the non-source files and how to compute it from other files. When you write a program, you should write a makefile for it, so that it is possible to use Make to build and install the program.


____________________

Non Terminal Xcode "Build System"

https://developer.apple.com/documentation/xcode/build-system

(Full documentation available internally, "Xcode" options "help" "developer documentation")

(((((((((((((((((((((( cloning GitHub repo into Xcode GUI )))))))))))))))))))))))))

How to Clone a project in Xcode.
https://ashley-oldham.medium.com/how-to-clone-a-project-in-xcode-843066d4b5dd

Firstly you want to open up the project page on github that you would like to clone. You should see a small row of three buttons reading ‘Go to file’, ‘Add file’ and lastly ‘Code’. If you click on this last button, you will see the link to which you will need to copy.

If you already have Xcode open, head to the Source control menu and click ‘Clone’. If not and you are launching Xcode, you can clone a project by clicking on ‘Clone’ from the welcome screen.

Last step is to save the cloned project to your computer. I always save my files within the same development folder so I know where all my project files are kept. Once this has been done, the project opens in Xcode and it’s yours to play with!

(tested, works,  OSX 14 Xcode 15, easy troll smash button style) :D



((((((((((((( developer documentation, Xcode, help, source control management "preferences" referance )))))))))))))

( Xcode 15, Xcode>settings = Xcode>preferences )
(one option to find this screen, when cloning a new repo,  is below)

open Xcode "splash screen"
option "clone git repository"
"enter repository URL" screen
click on "arrow icon" pointing to the right, next to text "personal and organizational repositories", for advanced settings "preferances" menu.


((((((((((((((((((( adding files to Xcode "project navigator folder" ))))))))))))))))))

drag and drop items from "finder" directly to "project navigator folder"

(possibility of adding build options arguments on this action)
( /usr/bin/make  referenced)

(after files drag and drop, folder info specifies "no configureable targets found")

( info, deployment target, no configureable targets found)

https://developer.apple.com/documentation/xcode/configuring-a-new-target-in-your-project

(Xcode15, new target, language: swift, only selectable option)


____________________
(Xcode GUI build notes)

clone repo
create new project, choose a template, (not sure which template yet)
project name
choose cloned repo folder
drag and drop cloned repo folder from finder to project navigator folder in Xcode



----------------------

Apple Developer Program Enrollment Link.

https://developer.apple.com/programs/enroll/

appears to be the log in location, for official stuff thingys, like the notarization signature, for build from GitHub Repo stuffs mentioned above.

-----------------------

**Comment by 2a5A1Ghu1** [comment]
The issue you are having is common among unsigned macOS software and thus common in the cryptocurrency space, please follow the instructions here if you would like to use the unsigned software. 

https://support.apple.com/en-us/HT202491

**Comment by squidicuzz** [comment]
> The issue you are having is common among unsigned macOS software and thus common in the cryptocurrency space, please follow the instructions here if you would like to use the unsigned software.
> 
> https://support.apple.com/en-us/HT202491

@mohker-83010 Please refer to this.

**Comment by squidicuzz** [comment]
OSX executable for `3.4.2` has been posted.  Though not signed.  We are working on correcting this...

**Comment by mohker-83010** [comment]
scc-3.4.2.3-qt-mac.dmg appears to be working. syncs up. havent tested functionallity yet. 🙂
