### ISSUE TITLE
Release 3.4.1 arm64

### ISSUE THREAD

**Issue by dddavid51** [stakecube/StakeCubeCoin#42]
Hello,
It would be possible to have a version 3.4.1 for the arm64 architecture for linux.
Thanks in advance.
David

**Comment by squidicuzz** [comment]
On it!  Will compile and post on the release for you.

**Comment by squidicuzz** [comment]
Please try this build: [scc-3.4.2.2-arm.zip](https://gir.sqdmc.net/dev/stakecube/files/scc-3.4.2.2-arm.zip)
Note: It is lacking the `scc-cli` component at the moment.  Once have that, I will post on the release.

I tested `scc-qt` on a Raspberry Pi 4b, with nvme drive as storage.  It did work.

----
5de5b502b44a4b1aac307d18b5ca011595fb8b2d99afc5ae3a96ac415a6852c0 => "scc-3.4.2.2-arm.zip"  ( 78,578,192 B / 74.94 MB )
218838cd6156fa2b970d9d7cf181618d7e17eee4a300edfc7577dbf8d9456a94 => "scc-qt"  ( 116,285,248 B / 110.90 MB )
dac25c6c46492e62c5ea7d56580012e7cced5d4cd2d6a6026e4d0150fb56c0b6 => "scc-tx"  ( 9,965,384 B / 9.50 MB )
c3b06cb231d1f1a6ff6ab7a632c64ef4bc99610c4ac607e57ab88b8145f2f138 => "scc-wallet"  ( 81,759,112 B / 77.97 MB )
febbd95df38bff2c0332759c7785c08f9eca7da437fc22c7e22a6cbd40ca9f30 => "sccd"  ( 81,262,672 B / 77.50 MB )

**Comment by squidicuzz** [comment]
The full arm64 release has been published: [scc-3.4.2.2-arm.zip](https://github.com/stakecube/StakeCubeCoin/releases/download/v3.4.2/scc-3.4.2.2-arm.zip)
