### ISSUE TITLE
QT wallet is larger than my screen

### ISSUE THREAD

**Issue by KenSharp** [stakecube/StakeCubeCoin#52]
This isn't new but I was hoping something would eventually be fixed as I suspect it may be an issue on my system, but I don't know where to start looking...

My resolution is set to 1080p, but since upgrading to Ubuntu Jammy (years ago) the SCC Core wallet is much larger than my screen.

Screenshot is of my entire desktop.

![scc](https://github.com/stakecube/StakeCubeCoin/assets/13607576/7ec4df78-1690-4837-aa77-21bce58c2865)

I do not know how to resolve this. If it is an issue with my setup then I'll happily file this with the relevant maintainers.

I'm used to using the CLI but it would be nice to use the GUI sometimes.

**Comment by KenSharp** [comment]
Workaround:
`QT_AUTO_SCREEN_SCALE_FACTOR=0 scc-qt`

**Comment by KenSharp** [comment]
Relevant docs:
[https://doc.qt.io/qt-5/highdpi.html](https://doc.qt.io/qt-5/highdpi.html)

**Comment by sac1978** [comment]
I had a similar issue and found it was the SCC-Qt.conf file had become corrupted. The file can be found in the home folder of the user you are running as or if sudo running in /root under that folder you will find .config folder (you will have to show hidden folders probably) then in there is a StakeCubeCoin folder and in that folder you will find the file SCC-Qt.conf. Rename that file to SCC-Qt.conf.old just in case, but removing this file should just reset all the default setting of the wallet. Start the wallet, then make sure you go back set the wallet settings as you like it as that all gets saved into that file, like showing Masternodes / coin control etc. When it starts up make sure you point it at the correct chain data location if you did not just use the default setting, if you did, just accept that again.
